spring.application.name=school-app

server.port=8080

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/school_app?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================
jwt.secret=9a67471ec97aa3da1034e409cf2106fce0b74cf03959da7e3977595e0c904121
jwt.access-expiration=3600000000000
jwt.refresh-expiration=604800000
jwt.otp-expiration=3000000000
jwt.reset-expiration=90000000

# ===============================
# MAIL - GMAIL SMTP
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=giapngo0310@gmail.com
spring.mail.password=wcavfimgpxvngupq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ===============================
# APP
# ===============================
app.name=School App
app.issuer=SchoolApp
app.server-ip=192.168.0.103
app.frontend-reset-url=http://${app.server-ip}:5173/#/reset-password?token=

# ===============================
# VNPAY SANDBOX
# ===============================
vnpay.tmn-code=TL6D7BHQ
vnpay.hash-secret=3K8QXM3OK9WNI2TYGYPCSAZPZSQT7RTW
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://${app.server-ip}:8080/api/tuition-payments/vnpay-return

